apiVersion: v1
data:
    LEARNMATE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:ODBV9NozG+JY+cR4qSMp647aEZ4VyiCzonckh8xZnF6EULpcDPxF+JiZi/s=,iv:v4GVSkEaUrsVdPsqgHePihunW9xuqCCmyT/Rg78OOqM=,tag:5cRoxRHWM20cB9eFHIKjyQ==,type:str]
    LEARNMATE_SEARCH_HOST: ENC[AES256_GCM,data:gh/F6NdS+ucwYSP7mJ+5SZTMuLfv27X/lLHoTmZZJzW37jylBR9zzFDZNbjrXiPH,iv:aZ9Q3t/ZfKr7qC6wxXkajOZ9yCqUhvIeCvRMO/oU64Q=,tag:e1GSuyYJFxKJalV4vH5NCA==,type:str]
    LEARNMATE_SEARCH_PASSWORD: ENC[AES256_GCM,data:ZD2/kaLcg2lwpO6gUtPLKB9r2mJwfNvz/vRK5w==,iv:PFAlv3Kj7+btkXxnj5nkJA4u7IyY8evnebT/YIbbV3o=,tag:x6Yq1rZiAEC2FkznUyBdzQ==,type:str]
    LEARNMATE_SEARCH_USERNAME: ENC[AES256_GCM,data:xh6SJvcluem/+Uj2kY2n/w==,iv:BAmr6E0h6zAPxJMz4RMoFgPE3C4NhUmGu2G8SWFlbi8=,tag:OATYWdkdDARDMfy/8j27zQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: secret-api-web
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://key-vault-learnmate-v1.vault.azure.net
          name: aks-learnmate-v1-sops-key
          version: 008267a8eeef4d4eb397bc5cc2037c0e
          created_at: "2024-05-27T20:10:57Z"
          enc: dBQvvXfnuQ38jM2JW5E0FSprFnoJ6O1RbaSKJleEIYrOF80epg-l5DRtvlRsMpbZuKy11Vowl25sQGBw8d62U9CRBwDcOgUelN9TWfI_mGrGnc1Q72taNH-4kC8uVJ0mjbfuv4qPDtj4rAtZBdrqLuqVonYN0xIZMzuYnum94mTFECkLXSe6m0WEMilxE2kKrrvBU8HOcFsLliY2tuI7W910TCjvvvF0dD_dv0lpAZ8CDFdiFO4zoJjquQlBJi1CPa12BgSaI38warBabaEXKjG2U-jDogR5CPdbALu6AsxRDcYr8JTtOKlu3IWEEbZtHitXOSqiMfCinIlrW8qIbw
    hc_vault: []
    age: []
    lastmodified: "2024-05-27T20:10:59Z"
    mac: ENC[AES256_GCM,data:5q4vQ/IxCQqvma0y9LjTwLZ9k652ROdMRFTiNKJlNmhGTtbwlLci5W65PG846+0jHOfPdNvaOefZESfpXPQXOtA1YpEds83JRFIVuEe8BCAH+/R/DhdUzWFfqa7Yj41eZb++MlDy6jNqWMklYMfNxVHQvZKuBnNZhdqrtzcM5pY=,iv:pqkvoUrKRnulU3NGONHa10cajtmNGHDAFB2FClz1ev8=,tag:plMbxLqeON3AfrL/MwlgHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
