apiVersion: v1
data:
    LEARNMATE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:e9PhTEquUUJwVK5sJKJ0dleRf9bPU+6XCVShblltGBOWC7LO5m7g6QjjZo0=,iv:unLo/hm5DlPWIQjokVINC8vzYWiFQ43v0xWJjlErzDo=,tag:S5kMfYJxsnTFn+7asr5mAw==,type:str]
    LEARNMATE_SEARCH_HOST: ENC[AES256_GCM,data:MHTRA41E+wXPy2t8QDov/WPywPHa5pMqgFtTfGIQe7QIQI/PUzW2crhoBMqalg81,iv:P1mBwpDm4IGxQtK9MxqdnYIKdwLjfkVxnidd3+r3Vtk=,tag:jRmT9x/oBCiFkV2hOD/JKg==,type:str]
    LEARNMATE_SEARCH_PASSWORD: ENC[AES256_GCM,data:4pz1t463OQ9S/ruhf5Ed2YxW+MF12cXLTbJbHQ==,iv:9e2Sz6BSeomnfn7ccHfG+9T254dGYFMCl5UE9QGmqio=,tag:+Z/+X/xHrSVPs8GT3coYPQ==,type:str]
    LEARNMATE_SEARCH_USERNAME: ENC[AES256_GCM,data:ijWQ2GeH59cp65sc6wAikA==,iv:f0XjUlsstDd8G+4p8bM/8Vo8++CVSRbr5aUuJh+iUwE=,tag:tynFzkoQBcuRRT+oWYkEqg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: secret-api-web
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://key-vault-lm-eu-v1.vault.azure.net
          name: aks-learnmate-v1-sops-key
          version: be60cfd98025419882b5ed458c360958
          created_at: "2024-06-01T11:50:18Z"
          enc: Vzn-SYQa10vA2B-f_kE_AksSx4q2dg6UE9lMdbBPWTM2d4SNM21gmg8WLD_thVV4TXpN970yjTYu0UayxjYagH3ywfrEMbACPHShIIk6-eUur-5MwSOe8ALBCGbjoI2XVFM-jisxHajlnp69C1D1L3biClHh0mTm5I1LwYwlcJ6-uaDJtxYHjo6tawo1YUW7h6L_Yos0hl-c-hucg3I110ZrD-hTKlPMah64sgBMZieGh-rqd0FdiJnOQF8dlkWsruoOOOD7P47A0n5O_P1Q_ItTg9btqS2na0bWp5uL4TaWoJkwIXpifK-G-nplDzMA2iqGfSO70NYecZEAScYQYw
    hc_vault: []
    age: []
    lastmodified: "2024-06-01T11:50:20Z"
    mac: ENC[AES256_GCM,data:aXjqE14mcDdIP+uiWKy7NnXT8/DVOpcezVYDmWke7qkhLkggDG9eXSqS25Za1q4/6e084jHFkI4mRTGnhpN+MVoC8om2hiKSIe3bJViuiuN4GaZCawgil1WQtiLJqvdxRxdSEgVJGjuny2TJ848YPJe3qMwD6GsEz4m7viSQRG4=,iv:jlpIc75KYnzhTIH+XN+tT1PIi/EXgAWHDlBHalciWgo=,tag:UlqqALjfZL9b/R59VeHj0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
