name: build-pipeline

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  JAVA_VERSION: '22'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn verify -B -ntp